// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCasas.Controllers;

#nullable disable

namespace WebApiCasas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230307060601_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiCasas.Entidades.Casa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ancho")
                        .HasColumnType("int");

                    b.Property<string>("calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("largo")
                        .HasColumnType("int");

                    b.Property<int>("numeroCasa")
                        .HasColumnType("int");

                    b.Property<int>("pisos")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Casas");
                });
#pragma warning restore 612, 618
        }
    }
}
