// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCasas.Controllers;

#nullable disable

namespace WebApiCasas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiCasas.Entidades.Casa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ancho")
                        .HasColumnType("int");

                    b.Property<string>("calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("largo")
                        .HasColumnType("int");

                    b.Property<int>("numeroCasa")
                        .HasColumnType("int");

                    b.Property<int>("pisos")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("WebApiCasas.Entidades.Habitante", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CURP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CasaID")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CasaID");

                    b.ToTable("Habitante");
                });

            modelBuilder.Entity("WebApiCasas.Entidades.Habitante", b =>
                {
                    b.HasOne("WebApiCasas.Entidades.Casa", "Casa")
                        .WithMany("habitantes")
                        .HasForeignKey("CasaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Casa");
                });

            modelBuilder.Entity("WebApiCasas.Entidades.Casa", b =>
                {
                    b.Navigation("habitantes");
                });
#pragma warning restore 612, 618
        }
    }
}
